services:
  mysql:
    image: mysql:8.0
    container_name: torchapp-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: torchapp
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

  backend:
    build: .
    container_name: torchapp-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/torchapp
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

      MAIL_USERNAME: ""
      MAIL_PASSWORD: ""
      MAIL_FROM: ""
      MAIL_FROM_NAME: "TorchApp"
    volumes:
      - ./uploads/users:/app/uploads/users
    depends_on:
      - mysql
    restart: always

volumes:
  mysql_data:
